export const questions = [
    ["Where was Chopin born?",
    "Poland",
    "Austria",
    "India",
    "Russia"],
    ["What was Chopin's instrument of choice?",
    "The Piano",
    "The Flute",
    "The Violin",
    "The Organ"],
    ["What type of music did Chopin focus on?",
    "Short Form Piano",
    "Symphonic Poem",
    "String Chamber Music",
    "Opera"],
    ["What did Chopin's father do for work?",
    "Lawyer",
    "Composer",
    "Teacher",
    "Banker"],
    ["Where did Chopin study Music?",
    "Warsaw Conservatory",
    "Moscow Conservatory",
    "Vienna Conservatory",
    "Paris Conservatory"]];

